### ISSUE TITLE
LoRaWAN.busy() stays true after gateway join but only when device can see multiple gateways

### ISSUE THREAD

**Issue by NetSensors** [GrumpyOldPizza/ArduinoCore-stm32l0#62]
I have been using this library for a while now and have had great results, recently though I have started deploying devices in the field and I have been seeing a number of failures. 

On closer inspection only the devices that can see more than one gateway fail. In one case a device is able to see 5 gateways and it fails in about 1 in three join attempts. 

That is the join on the gateway side seems to be successful but on the device the lorawan.busy() flag stays at true and never seems to release no timeout just stays busy.

I'm using the TTN network in the UK on 868 the gateways are generally kerlink. Below is the code I am using to  initialise LoraWAN. 

It's not a signal strength issue the gateways a reporting RSSI values of -55 to -108. When i save session information with LoRaWAN.setSaveSession(true) then there are no issues as registration does not occur. 

My thoughts were that the gateway response was not being received or corrupted by other gateways trying to respond at the same time to the Join request and there being an issue with any timeout on the lorawan.busy() function other than that ??  

`// LORAWAN Initialisation
  LoRaWAN.getDevEui(devEui,18);
  Serial.print("Device EUI: ");Serial.println(devEui);
  
  LoRaWAN.begin(EU868);
  LoRaWAN.setDutyCycle(false);
  LoRaWAN.setADR(true);
  //LoRaWAN.setSaveSession(true);
  //LoRaWAN.setReceiveDelay(6000);
  //LoRaWAN.setDownLinkDwellTime(true);
  //LoRaWAN.setPublicNetwork(true);
    
  LoRaWAN.setLinkCheckLimit(16);
  LoRaWAN.setLinkCheckDelay(8);
  LoRaWAN.setLinkCheckThreshold(4);

  //LoRaWAN.onJoin(joinCallback);
  //LoRaWAN.onLinkCheck(checkCallback);
  LoRaWAN.onTransmit(doneCallback);
  LoRaWAN.onReceive(receiveCallback);
  
  LoRaWAN.joinOTAA(appEui, appKey, devEui);
  Serial.println("JOIN( )");`

**Comment by GrumpyOldPizza** [comment]
Ack ;-)

No idea what that could be and no idea how to debug that. 

In theory the code tries 3 times and then gives up (resetting busy, line 3524, LoRaWAN.cpp). So assuming there is corruption because more than one gateways answers (which should not be the case), it should not matter, because the code would retry, using a new "devNonce", so that a gateway would see a new join attempt. And it seems unlikely that more than one gateway would consistently corrupt the signal back to back.

The code had been tested that it would give up after the right number of attempts. It had been tested that it would do the right thing it the LoRaMac-node stack would return an error.

**Comment by NetSensors** [comment]
I have investigated further and this appears to be a gateway issue as we are seeing it with other LoRaWAN modules.
